### ISSUE TITLE
Carto Map doesn't work in Collection View (scrolling around)

### ISSUE THREAD

**Issue by liamcharmer** [nativescript-community/ui-carto#2]
Heres an example repo. 

https://github.com/liamcharmer/Carto-In-CollectionView-nativescript

But it doesn't seem that the map allows dragging around within a CollectionView.

**Comment by farfromrefug** [comment]
@liamcharmer i have looked at it and there might be something in carto. Could you try with another map plugin?
The best would be to try with this https://github.com/tjvantoll/nativescript-maps/blob/master/maps.ios.js. Though it is not maintained anymore. If it works with other maps then it would be good to report your issue in the carto sdk repo https://github.com/CartoDB/mobile-sdk

For reference this is what should be used to make it work https://developer.apple.com/documentation/uikit/uiview/1622453-exclusivetouch. But i tried and it does not seem to work.

**Comment by liamcharmer** [comment]
I've updated my repo to include google map (just for iOS i haven't included android files and also removed the API key to be placed).

Seems that the google maps plugin works fine in the collectionview. I'll throw an issue request into CartoDB. 

For now I guess using google-maps should be fine.

**Comment by liamcharmer** [comment]
I also put the map inside just a scrollview, and the same issue happens

**Comment by liamcharmer** [comment]
Allows for horizontal scrolling (when inside a vertical scrollview/collectionview).

**Comment by liamcharmer** [comment]
Interesting to note, I have just tested the google-maps on Android, and you are not able to scroll around within the map in the list view. So on iOS it seemed fine, but Android nope.
